theme: jekyll-theme-tactile
title: Overcast Coffee Company
description: Serving Empire Street Espresso, breakfast and lunch, and crepes!
  Monday-Friday 6:30a-4:00p
  Saturdays soon!
  [312 15th ave E, Seattle, Washington 98112](https://goo.gl/maps/Q6JbtJcBRuD5KVTt9)
